### PR TITLE
Backend prep for v1

### PR DESCRIPTION
**Pull request by Trivinyx**
**New:**
- ENVIROMENT variable to set dev or production.
- prod disables the api docs.

**Changes:**
- change to deploy action to accomandate the new env var
- removed temporary devOnly
- removed testproject creation endpoint
- updated env.example

### CODE REVIEW

**Comment by Trivinyx** [comment]
this branch is not locally tested yet, please test and check if it works, secondary i want opinions if it is more to be done in the prep of backend

**Comment by Trivinyx** [comment]
Need to fix the docker-compose comunication

**Review by Trivinyx — COMMENTED** [review]
^

**Review by ostepizza — APPROVED** [review]
lgtm and ting
image

**Pull request merged**
