### PR TITLE
Extra Help Messages & Help Modal

### PR DESCRIPTION
**Pull request by ostepizza**
This pull request adds some extra feedback for the user, and a help modal, to attempt with making the application easier to use. In addition, several recorded gifs explaining how to use the application has been added.

Help messages:
As noted during user testing, some users were unaware of the points needed for the georef to work. A counter has been added, such as "2 more points needed to georeference".

Help modal:
To the left of the Feedback-button, there is now a Help button. This opens up a modal containing several pages with information about how to use the app, including:
- Introduction - What is georeferencing?
- Navigating around - Navbar **(has gif)**
- Navigating around - Split View **(has gif)**
- Navigating around - Overlay **(has gif)**
- Navigating around - Crop Mode **(has gif)**
- Adding Points (has gif)
- The Split View Toolbar
- The Overlay Toolbar
- The Coordinate Table **(has gif)**
- Help Modal
- Feedback Form
- Download File
- Exiting The Editor

### CODE REVIEW

**Review by Trivinyx — COMMENTED** [review]
I have looked at the code part, it looks god. (github mobile win) But don't have the oppertunety to test atm. So a comment😉 If you get @GlennJoakimB to test he can approve

**Comment by Trivinyx** [comment]
Neeed darkmode fix
image

**Comment by Trivinyx** [comment]
image

**Comment by Trivinyx** [comment]
Something wired with scale on the modal or intended?
image

**Comment by Trivinyx** [comment]
After fix:
image

**Review by GlennJoakimB — APPROVED** [review]
👍

**Pull request merged**
