### PR TITLE
textualrev

### PR DESCRIPTION
**Pull request by Meepception**

### CODE REVIEW

**Review by ostepizza — CHANGES_REQUESTED** [review]
Will unfortunately not approve, needs text on Text2Map, and perhaps use the component that renders Image or PDF based on URL.

**Comment by ostepizza** [comment]
> Will unfortunately not approve, needs text on Text2Map, and perhaps use the component that renders Image or PDF based on URL.

mb g, forgot that the ServiceName-component isn't in this branch, so disregard my comment on that :d

**Comment by Meepception** [comment]
> Will unfortunately not approve, needs text on Text2Map, and perhaps use the component that renders Image or PDF based on URL.

Text2Map part intentionally left blank due to potentially getting cut/unsure of what should contain, as per discussed earlier

**Review by ostepizza — APPROVED** [review]

**Review by Lennern — APPROVED** [review]
gj, boys

**Pull request merged**
